/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'pd': RouteRecordInfo<'pd', '/pd', Record<never, never>, Record<never, never>>,
    'pip': RouteRecordInfo<'pip', '/pip', Record<never, never>, Record<never, never>>,
    'ptk': RouteRecordInfo<'ptk', '/ptk', Record<never, never>, Record<never, never>>,
    'tarik-pd': RouteRecordInfo<'tarik-pd', '/tarik/pd', Record<never, never>, Record<never, never>>,
    'tarik-ptk': RouteRecordInfo<'tarik-ptk', '/tarik/ptk', Record<never, never>, Record<never, never>>,
  }
}
